# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

config:
  version-candidate: VERSION

build:
#  quality:
#
  correctness:
    build:
      image: typedb-ubuntu-22.04
      command: |
        sudo apt update
        sudo apt install -y libclang-dev
        bazel run @typedb_dependencies//tool/bazelinstall:remote_cache_setup.sh
        bazel build //... 

release:
  filter:
    owner: typedb
    branch: [master]

  deployment:
    deploy-github:
      image: typedb-ubuntu-22.04
      command: |
        export PYENV_ROOT="/opt/pyenv"
        pyenv install 3.7.9
        pyenv global 3.7.9
        sudo unlink /usr/bin/python3
        sudo ln -s $(which python3) /usr/bin/python3
        sudo ln -s /usr/share/pyshared/lsb_release.py /opt/pyenv/versions/3.7.9/lib/python3.7/site-packages/lsb_release.py
        python3 -m pip install certifi
        export DEPLOY_GITHUB_TOKEN=$REPO_GITHUB_TOKEN
        bazel run --define version=$(cat VERSION) //:deploy-github -- $FACTORY_COMMIT